const PRODUCTS = [
  {
    id: 1,
    name: "プレミアム Tシャツ",
    price: 3500,
    category: "ファッション",
    image: "https://placehold.co/300x300/4F46E5/white?text=T-Shirt",
    description: "高品質コットン使用の定番Tシャツ。",
  },
  {
    id: 2,
    name: "スニーカー",
    price: 12000,
    category: "ファッション",
    image: "https://placehold.co/300x300/059669/white?text=Sneaker",
    description: "軽量で快適な毎日のスニーカー。",
  },
  {
    id: 3,
    name: "ワイヤレスイヤホン",
    price: 8800,
    category: "電子機器",
    image: "https://placehold.co/300x300/DC2626/white?text=Earphone",
    description: "ノイズキャンセリング対応のワイヤレスイヤホン。",
  },
  {
    id: 4,
    name: "スマートウォッチ",
    price: 25000,
    category: "電子機器",
    image: "https://placehold.co/300x300/D97706/white?text=Watch",
    description: "健康管理・通知対応のスマートウォッチ。",
  },
  {
    id: 5,
    name: "ステンレスボトル",
    price: 2800,
    category: "生活用品",
    image: "https://placehold.co/300x300/0891B2/white?text=Bottle",
    description: "保温・保冷24時間対応のボトル。",
  },
  {
    id: 6,
    name: "ノートパッド",
    price: 1200,
    category: "文具",
    image: "https://placehold.co/300x300/7C3AED/white?text=Notepad",
    description: "書き心地抜群のA5ノート。",
  },
];
